### ISSUE TITLE
syscallstubs seem to malfunction

### ISSUE THREAD

**Issue by jfmaes** [TheWover/DInvoke#11]
There's something going wrong with the syscall stubs or the invocation explanation on the blogpost. 
when tested using regopenkey,regwritevalue,regclose, it seems the syscalls work, but the object attributes get misinterpreted for some reason. 

when testing using manualmap or overload, the functionality seems fine.

**Comment by TheWover** [comment]
Not sure about that exactly, but I'm planning on replacing the syscall stub generation logic so I will close this Issue for now and create a second one for that update.
