### ISSUE TITLE
OverloadModule / MapModuleFromDisk not working with export forwards

### ISSUE THREAD

**Issue by s0rtega** [TheWover/DInvoke#17]
### Description
Using **MapModuleFromDisk** or **OverloadModule** in functions with export forwards (e.g., `netapi32.dll!NetLocalGroupAddMembers`) and then calling `CallMappedDLLModuleExport` will not work in all cases. After resolving the forward, the function tries to find the new module in the process PEB: https://github.com/TheWover/DInvoke/blob/af9f86984a2ce329cb44a97459592f0b191fe252/DInvoke/DInvoke/DynamicInvoke/Generic.cs#L484 but the process will not necessarily have the module loaded which will return System.AccessViolationException.

### Potential fix
When `hModule` returns null, include a second step to load the dll from disk using the same method (Overload / MapModule). This assumes that the .dll is in the same directory but maybe there is a more elegant solution. 

### Test code

```
using System;
using System.Runtime.InteropServices;

namespace overload_poc
{
    class STRUCTS
    {
        [StructLayout(LayoutKind.Sequential)]
        public struct LOCALGROUP_MEMBERS_INFO_3
        {
            [MarshalAs(UnmanagedType.LPWStr)]
            public string domainandname;
        }
    }

    class DELEGATES
    {
        [UnmanagedFunctionPointer(CallingConvention.StdCall)]
        public delegate DInvoke.Data.Native.NTSTATUS NetLocalGroupAddMembers(
            string servername,
            [MarshalAs(UnmanagedType.LPWStr)]
            string groupName,
            UInt32 level,
            ref STRUCTS.LOCALGROUP_MEMBERS_INFO_3 info,
            UInt32 totalentries);
    }
    class Program
    {
        static void Main(string[] args)
        {

            // NetLocalGroupAddMember (forwarded to SAMCLI.NetLocalGroupAddMember)
            DInvoke.Data.PE.PE_MANUAL_MAP mappedDLL = DInvoke.ManualMap.Map.MapModuleFromDisk(@"C:\Windows\System32\SAMCLI.dll");

            String group = @"Administrators";
            STRUCTS.LOCALGROUP_MEMBERS_INFO_3 username = new STRUCTS.LOCALGROUP_MEMBERS_INFO_3();
            username.domainandname = @"myUser";

            object[] funcParams =
                {
                    null,
                    group,
                    (UInt32)3,
                    username,
                    (UInt32)1};

            DInvoke.Data.Native.NTSTATUS res = (DInvoke.Data.Native.NTSTATUS)DInvoke.DynamicInvoke.Generic.CallMappedDLLModuleExport(
                                        mappedDLL.PEINFO, 
                                        mappedDLL.ModuleBase,
                                        "NetLocalGroupAddMembers", 
                                        typeof(DELEGATES.NetLocalGroupAddMembers), 
                                        funcParams,
                                        false);
        }
    }
}
```

**Comment by s0rtega** [comment]
Just as a side note, even if I am passing the forwarded library directly (`DInvoke.Data.PE.PE_MANUAL_MAP mappedDLL = DInvoke.ManualMap.Map.MapModuleFromDisk(@"C:\Windows\System32\SAMCLI.dll");`) I get AccessViolation. But If I call it using `GetLibraryAddress `and then `DynamicAPIInvoke` it executes. 

I was some debugging but I was not able to identify the cause. Based on my testing, the memory looks the same in both cases and the Ptr is pointing the right memory region, but maybe there is something that I am missing. Anybody is able to replicate the issue?

**Comment by TheWover** [comment]
I fixed the issue of not being able to load things that aren't in the PEB. The change is in `dev`. Not sure what your other issue is, thought, tbh... In the meantime I would recommend not using `MapModuleFromDisk`. It maps a file into a Section, but that file does not have all of the fixups done to it that the Windows loader does after mapping a file to an image. The only reason that function is there is because it is used in Module Overloading. To clarify this confusing issue, I renamed `MapModuleFromDisk` to `MapModuleFromDiskToSection`. If you wish to manually map a file from disk into a section I would recommend using `OverloadModule` while passing in the same DLL name for both the decoy module and the payload DLL. This will ensure that the DLL has all the fixups it needs. Except in your test case where it fails when `GetLibraryAddress` works 😂 . That's another issue I will need to track down. Would you mind making a separate issue for that?

**Comment by s0rtega** [comment]
Sounds good. I was trying the changes this morning and everything was working OK. I have also created another PR to push some changes and have better control on the workflow, take a look into that and merge the changes if you consider that can be useful and are not breaking anything. 

I will open now the second issue. I have been doing more debugging on that and I was not able to fix anything so hopefully you will have better luck. I am closing the issue, thanks!
